### ISSUE TITLE
config-server setting

### ISSUE THREAD

**Issue by takealook97** [underthekey/udtk-engine#1]
## 📋 description
- config-server build

## ✅ todo
- [x] add config data to udtk-config repository
- [x] set config-server module
- [x] config-data fetch test

## 💬 etc
-
