### ISSUE TITLE
gateway-server setting

### ISSUE THREAD

**Issue by takealook97** [underthekey/udtk-engine#3]
## 📋 description
- build gateway-server

## ✅ todo
- [x] build kafka server (local)
- [ ] set uri to load balacing for auto scaling
- [x] test config-server data fetching
- [x] gateway feature test

## 💬 etc
-
