### ISSUE TITLE
api specification

### ISSUE THREAD

**Issue by takealook97** [underthekey/udtk-engine#7]
## 📋 description
- make api specification

## ✅ todo
- [ ] set end point
- [ ] draft details
- [ ] specify request & response
- [ ] draft error message per endpoint

## 💬 etc
-
