### ISSUE TITLE
proxmox database server build

### ISSUE THREAD

**Issue by takealook97** [underthekey/udtk-engine#9]
## 📋 description
- build database server

## ✅ todo
- [x] add mariaDB container
- [x] add redis container
- [x] add minio container

## 💬 etc
- route to target server
